package entities;
// Generated Oct 14, 2015 9:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="Order"
    ,schema="dbo"
    ,catalog="FairDeal"
)
public class Order  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Employee employee;
     private Date orderDate;
     private Boolean isActive;
     private Set<OrderLine> orderLines = new HashSet<OrderLine>(0);

    public Order() {
    }

	
    public Order(Employee employee) {
        this.employee = employee;
    }
    public Order(Customer customer, Employee employee, Date orderDate, Boolean isActive, Set<OrderLine> orderLines) {
       this.customer = customer;
       this.employee = employee;
       this.orderDate = orderDate;
       this.isActive = isActive;
       this.orderLines = orderLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CustomerID")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SellerID", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OrderDate", length=23)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderLine> getOrderLines() {
        return this.orderLines;
    }
    
    public void setOrderLines(Set<OrderLine> orderLines) {
        this.orderLines = orderLines;
    }




}


