package entities;
// Generated Oct 14, 2015 9:28:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="Product"
    ,schema="dbo"
    ,catalog="FairDeal"
)
public class Product  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private String productName;
     private Long unitPrice;
     private Integer quantity;
     private Long importPrice;
     private Boolean isActive;
     private Set<OrderLine> orderLines = new HashSet<OrderLine>(0);

    public Product() {
    }

    public Product(Category category, String productName, Long unitPrice, Integer quantity, Long importPrice, Boolean isActive, Set<OrderLine> orderLines) {
       this.category = category;
       this.productName = productName;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
       this.importPrice = importPrice;
       this.isActive = isActive;
       this.orderLines = orderLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CategoryID")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="ProductName")
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="UnitPrice", precision=18, scale=0)
    public Long getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Long unitPrice) {
        this.unitPrice = unitPrice;
    }

    
    @Column(name="Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="ImportPrice", precision=18, scale=0)
    public Long getImportPrice() {
        return this.importPrice;
    }
    
    public void setImportPrice(Long importPrice) {
        this.importPrice = importPrice;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<OrderLine> getOrderLines() {
        return this.orderLines;
    }
    
    public void setOrderLines(Set<OrderLine> orderLines) {
        this.orderLines = orderLines;
    }




}


