package entities;
// Generated Oct 14, 2015 9:28:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleAction generated by hbm2java
 */
@Entity
@Table(name="Role_Action"
    ,schema="dbo"
    ,catalog="FairDeal"
)
public class RoleAction  implements java.io.Serializable {


     private Integer id;
     private Action action;
     private Role role;

    public RoleAction() {
    }

    public RoleAction(Action action, Role role) {
       this.action = action;
       this.role = role;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ActionID", nullable=false)
    public Action getAction() {
        return this.action;
    }
    
    public void setAction(Action action) {
        this.action = action;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RoleID", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


