package entities;
// Generated Oct 14, 2015 9:28:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="Role"
    ,schema="dbo"
    ,catalog="FairDeal"
)
public class Role  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean isActive;
     private Set<RoleAction> roleActions = new HashSet<RoleAction>(0);
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Role() {
    }

    public Role(String name, Boolean isActive, Set<RoleAction> roleActions, Set<Employee> employees) {
       this.name = name;
       this.isActive = isActive;
       this.roleActions = roleActions;
       this.employees = employees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<RoleAction> getRoleActions() {
        return this.roleActions;
    }
    
    public void setRoleActions(Set<RoleAction> roleActions) {
        this.roleActions = roleActions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


